apiVersion: v1
kind: Service
metadata:
  name: webapp-sql
spec:
  selector:
    app: mysql
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app
  labels:
    app: mysql
    tier: frontend
spec:
  selector:
    matchLabels:
      app: mysql
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: frontend
    spec:
      containers:
      - name: webapp1
        image: eu.gcr.io/gitops-cluster/chatbot:0.0.28
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: mysql
