apiVersion: v1
kind: Service
metadata:
  name: webapp-sql
spec:
  selector:
    app: mysql
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: mysql
    tier: frontend
spec:
  selector:
    matchLabels:
      app: mysql
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: frontend
    spec:
      containers:
      - name: webapp1
        image: eu.gcr.io/gitops-cluster/chatbot:0.0.26
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root-password
              name: mysql-secret
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user-name
              name: mysql-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name:  mysql-secret 
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
