apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webshop
  namespace: default
  labels:
    app: flask-webshop
spec:
  selector:
    matchLabels:
      app: flask-webshop
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-webshop
    spec:
      containers:
      - name: webshop-service
        image: eu.gcr.io/gitops-cluster/webshop-service:0.0.2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-webshop
spec:
  selector:
    app: flask-webshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer